title: Igreja Gnóstica Fraternidade da Luz
description: A busca rigorosa pela verdade e pela iluminação interior através do conhecimento (Gnose).
url: "https://prgsouza.com.br"
baseurl: "/igrejagnostica"