title: Igreja Gnóstica Fraternidade da Luz
description: A busca rigorosa pela verdade e pela iluminação interior através do conhecimento (Gnose).
url: "" # Deixe vazio por enquanto. O GitHub Pages preenche isso automaticamente.
baseurl: "" # Útil se o site não estiver na raiz do domínio (ex: /fraternidade)